
services:
  mongodb:
    image: mongo:latest
    container_name: meetupmongo_container
    ports:
      - "27017:27017"
    environment:
        SPRING_DATA_MONGODB_HOST: localhost
        SPRING_DATA_MONGODB_PORT: 27017
        SPRING_DATA_MONGODB_DATABASE: myEventDb

    volumes:
      - mongo_data:/data/db

  app:
    image: studentmeetup-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: localhost
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: myEventDb
    depends_on:
      - mongodb

volumes:
  mongo_data:
