services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "28017:27017"
    volumes:
      - mongo_data:/data/db

  app1:
    image: studentmeetup-app
    container_name: app-container-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_MONGODB_URI: mongodb://mongodb:27017/myEventDb
      JAVA_TOOL_OPTIONS: -Dspring.mongodb.uri=mongodb://mongodb:27017/myEventDb
      SKIDDLE_API_KEY: 1910d46f579d056bcf7c993d26b221c6
    depends_on:
      - mongodb

  app2:
    image: studentmeetup-app
    container_name: app-container-2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_MONGODB_URI: mongodb://mongodb:27017/myEventDb
      JAVA_TOOL_OPTIONS: -Dspring.mongodb.uri=mongodb://mongodb:27017/myEventDb
      SKIDDLE_API_KEY: 1910d46f579d056bcf7c993d26b221c6
    depends_on:
      - mongodb

  app3:
    image: studentmeetup-app
    container_name: app-container-3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_MONGODB_URI: mongodb://mongodb:27017/myEventDb
      JAVA_TOOL_OPTIONS: -Dspring.mongodb.uri=mongodb://mongodb:27017/myEventDb
      SKIDDLE_API_KEY: 1910d46f579d056bcf7c993d26b221c6
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

volumes:
  mongo_data: