
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "28017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: studentmeetup-app
    container_name: studentmeetup-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_MONGODB_URI: mongodb://mongodb:27017/myEventDb
      JAVA_TOOL_OPTIONS: -Dspring.mongodb.uri=mongodb://mongodb:27017/myEventDb
      SKIDDLE_API_KEY: 1910d46f579d056bcf7c993d26b221c6
    depends_on:
      - mongodb

volumes:
  mongo_data:
