spring.application.name=StudentMeetUp

# MongoDB - Docker container port 28017
spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:28017/myEventDb}
spring.data.mongodb.auto-index-creation=true

# Skiddle API Key
external.skiddle.api-key=${SKIDDLE_API_KEY:1910d46f579d056bcf7c993d26b221c6}

# Server Port
server.port=8080