spring.application.name=StudentMeetUp
spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:28017/myEventDb}
spring.data.mongodb.auto-index-creation=true
external.skiddle.api-key=${SKIDDLE_API_KEY:1910d46f579d056bcf7c993d26b221c6}
server.port=8080
server.forward-headers-strategy=framework
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.override-with-generic-response=false